#!/usr/bin/env python

import logging
from pathlib import Path

import pandas as pd
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import train_test_split

estimator = AdaBoostRegressor

logging.basicConfig(
    datefmt="%Y-%m-%dT%H:%M:%S",
    level=logging.DEBUG,
    format="[%(asctime)s] %(levelname)8s %(message)s",
)


def clean(data: pd.DataFrame) -> pd.DataFrame:
    logging.info("Cleaning")
    return data


def evaluate(model: estimator, X_test: pd.DataFrame, y_test: pd.DataFrame) -> None:
    logging.info("Score: %s", model.score(X_test, y_test))


def load() -> pd.DataFrame:
    path = Path("data/diamonds.csv")
    logging.info("Loading %s", path)
    return pd.read_csv(path)


def split(data: pd.DataFrame) -> list[pd.DataFrame]:
    logging.info("Splitting")
    X, y = data.drop(columns=["price"]), data["price"]
    return train_test_split(X, y, random_state=42)


def train(X_train: pd.DataFrame, y_train: pd.DataFrame) -> estimator:
    logging.info("Training AdaBoost Regressor")
    model = estimator()
    model.fit(X_train, y_train)
    return model


data = clean(load())
X_train, X_test, y_train, y_test = split(data)
model = train(X_train, y_train)
evaluate(model, X_test, y_test)
